apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  labels:
    app:  {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
  name: {{ template "name" . }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: {{ .Values.pv.storageSize }}
  csi:
    driver: disk-csi-driver.mks.ycloud.io
    volumeHandle: {{ template "name" . }}
    readOnly: false
    fsType: ext4
  persistentVolumeReclaimPolicy: {{ .Values.pv.reclaimPolicy }}
  storageClassName: yc-network-hdd