image: docker.io/archaron/nats-streaming-server:v0.14.2
imagePullPolicy: IfNotPresent

replicas: 1

storageSize: 1Gi
# optional
volumeSubPath: nats-streaming

pv:
#  serverUrl: 'FAKED'
  reclaimPolicy: Retain
  storageSize: 2Gi
