image: docker.io/canhnt/nats-streaming-server:v0.6.0
imagePullPolicy: IfNotPresent

replicas: 1

storageSize: 1Gi
# optional
volumeSubPath: nats-streaming

pv:
#  serverUrl: 'FAKED'
  reclaimPolicy: Retain
  storageSize: 2Gi
